### ISSUE TITLE
how to get amount of data which was uploaded and downloaded?

### ISSUE THREAD

**Issue by bizibizi** [pomozoff/VpnPhone#1]

**Comment by pomozoff** [comment]
I'm sorry, seems like I wasn't in my mind when I wrote it. Can't remember what it was. Anyway, check [this project](https://developer.apple.com/library/archive/samplecode/SimpleTunnel/Listings/SimpleTunnelServices_util_swift.html#//apple_ref/doc/uid/TP40016140-SimpleTunnelServices_util_swift-DontLinkElementID_15), it looks like what you need.
